services:
  - type: web
    name: asl-translate-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
      mkdir -p /opt/render/project/src/backend/app/models
      cp -r app/models/* /opt/render/project/src/backend/app/models/
    startCommand: |
      python app/check_model.py
      python app/fix_imports.py
      uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 10000 