services:
  - type: web
    name: asl-translate-backend
    env: python
    buildCommand: |
      echo "Starting build process..."
      pip install --upgrade pip
      pip install -r requirements.txt
      echo "Creating directories..."
      mkdir -p /opt/render/project/src/backend/app/models/weights
      echo "Copying model files..."
      cp -r app/models/* /opt/render/project/src/backend/app/models/ || echo "No model files to copy"
      echo "Copying weights file..."
      if [ -f "app/models/weights/cnn_model.pth" ]; then
        echo "Found weights file at app/models/weights/cnn_model.pth"
        cp app/models/weights/cnn_model.pth /opt/render/project/src/backend/app/models/weights/cnn_model.pth
      fi
      if [ -f "app/models/weights/new_cnn_model.pth" ]; then
        echo "Found weights file at app/models/weights/new_cnn_model.pth"
        cp app/models/weights/new_cnn_model.pth /opt/render/project/src/backend/app/models/weights/new_cnn_model.pth
      fi
      echo "Listing model directory contents:"
      ls -la /opt/render/project/src/backend/app/models/
      echo "Listing weights directory contents:"
      ls -la /opt/render/project/src/backend/app/models/weights/
    startCommand: |
      echo "Starting application..."
      uvicorn app.main:app --host 0.0.0.0 --port $PORT --log-level debug
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: PORT
        value: 10000
      - key: ENVIRONMENT
        value: production
      - key: LOG_LEVEL
        value: debug
    healthCheckPath: /health
    autoDeploy: true 